### ISSUE TITLE
Lab 2 anwers to questions

### ISSUE THREAD

**Issue by Mayrismt** [Watts-College/paf-511-template#1]
Hello everyone,

I received some questions from you regarding today's lab. I'm posting my responses here so everyone has access to them, can review them, and consider them for their assignments. 

1)	When do we use or need a Bonferroni corrected alpha? In the reading it showed a t-test for treatment villages and comparison villages, do we only use the Bonferroni corrected alpha for t-tests where more than one contrast happens? **YES, we use this when we have multiple contrasts.** 
2)	So we would need a corrected alpha for Q6 and Q7 to test true significance? **NO, Each question is only asking to compute a contrast under the same characteristic, and not multiple contrasts at the same time.**  This is to say that Q6 asks to compare age at the time of nonprofit formation- just one characteristic. Q7 asks to compare income levels prior to starting the nonprofit – just one characteristic.
3)	In regards to the questions in Q8, my understanding is that if any of the contrasts show significant difference, then the groups are not equivalent. Is that the right thought? **Yes, you’re on the right track.** 
4)	In the case of Q1, there are technically five contrasts taking place, right? Would I need a corrected alpha for this? The p-value is .36 so it wouldn't change my answer, but I am just unsure when exactly to get a corrected alpha.  Q**1 is not asking for a corrected alpha.** Your solutions will be the chi square test for the male and female entrepreneurs educational level, and your response to, highest level of educational obtainment achieved. You’ll use the values produced with the  t <- table line of code.
5)	Q7: Why would the chi square be not significant but the t test be extremely significant? **This question requires a t test. -**--The t-test and the chi-square test are two different statistical tests used for different types of data. The t-test is used to compare the means of two groups and is suitable for continuous numerical data. On the other hand, the chi-square test is used to examine the association between two categorical variables.-----What you need in this exercise is to conduct a t test, because of the type of data. This is a difference in means for median income for females and males. How much in average to each of these groups made when they started a non profit?? Is this difference significant? What’s your alpha? What’s the p-value??
6)	For the lab on question 8, since the p-value for the age variable is lower than 0.005. I understand that we could not claim group equivalency for the study but I am wondering since question 8 overall asks if the resources entrepreneurs have are equivalent, do we answer this differently? Would age count as a resource? **First you need to do a Bonferroni correction, since you have 7 contrasts. So you’ll have a new alpha to compare with and to draw conclusions. Yes, age is a variable.**

**Comment by SwestCodes** [comment]
HI Professor Tirado, so for question 8a, we need to do a bonferroni alpha and then compare all p-values to that in order to answer that question correctly?

**Comment by Mayrismt** [comment]
@swest235 > HI Professor Tirado, so for question 8a, we need to do a bonferroni alpha and then compare all p-values to that in order to answer that question correctly? Yes, exactly :)
